global/sharedcountertest:
  url: "/api/v1/counter"
  policy: "global/sharedcountertest"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
global/OAuthTest:
  url: "/oauth/example"
  policy: "global/OAuthTest"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
